# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nilssanderson.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ['node_modules']

# Prose editor
prose:
  rooturl: '_posts'
  siteurl: 'http://prose.github.io/taleofthetadpole/'
  relativeLinks: 'http://prose.github.io/taleofthetadpole/links.jsonp'
  media: 'media'
  metadata:
    _posts:

      # Category
      - name: "category"
        field:
          element: "multiselect"
          label: "Category"
          placeholder: "Choose Category"
          options:
            - name: "Blog"
              value: "blog"

      # Layout
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      # Title
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""

      # Splash
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""

      # Tags
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
